#!/usr/bin/env python3
"""Build the single-file `ai` executable from src/ fragments.

Why this exists
---------------
The shipped artifact is ONE file (`ai`) so that install.sh and the in-app
`/update` stay trivial (curl one file, swap it). But editing a ~2000-line
monolith is painful, so development happens in src/*.py. This script
concatenates those fragments, in dependency order, back into the single `ai`.

Rules for fragments
-------------------
* Modules must NOT import each other. There are no `from termux_ai...`,
  `from .x import ...`, or `import termux_ai` statements — fragments rely on
  the concatenation order below for name availability. This is checked.
* Stdlib imports live in src/_header.py (duplicates elsewhere are harmless but
  discouraged).
* All module-level globals (CONFIG_DIR, C, IS_TTY, est_tok, PRICING, ...) live
  in src/_constants.py so every later fragment can see them.

Usage
-----
    python3 build.py        # regenerate ./ai from src/

A git pre-commit hook (.githooks/pre-commit) runs this automatically and
refuses to commit if the generated `ai` is stale.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "src"
OUT = ROOT / "ai"

# Dependency order: everything a fragment needs must appear above it.
ORDER = [
    "_header",      # shebang, docstring, stdlib imports, __version__
    "_constants",   # paths, C colors, IS_TTY, est_tok, PRICING, parse_value...
    "fileio",       # FileReader
    "ui",           # MarkdownFormatter, Spinner
    "termux_api",   # TermuxAPI
    "server",       # ServerManager
    "db",           # Database
    "config",       # Config
    "tools",        # Tools (+ Plan-mode read-only executor)
    "backends",     # Backend, OpenAICompatible, AnthropicBackend, get_backend
    "app",          # App
    "cli",          # main() + __main__ guard
]

# Forbid cross-module imports — they'd silently break after concatenation.
# (No trailing \b: it would falsely reject `from .ui` since `\w` lands mid-word.)
FORBIDDEN = re.compile(r"^\s*(from\s+termux_ai|from\s+\.\w|import\s+termux_ai)", re.MULTILINE)

AUTOGEN = ("# AUTO-GENERATED by build.py from src/ \u2014 do not edit `ai` directly; "
           "edit src/ and re-run: python3 build.py\n")


def main() -> int:
    parts = []
    for name in ORDER:
        path = SRC / f"{name}.py"
        if not path.exists():
            sys.exit(f"build: missing fragment {path}")
        text = path.read_text()
        if FORBIDDEN.search(text):
            sys.exit(f"build: {name}.py has a forbidden cross-module import "
                     f"(fragments rely on concatenation order, not imports)")
        if name != "_header":
            text = f"# \u2550\u2550 termux_ai.{name} \u2550\u2550 (fragment; merged by build.py)\n" + text
        parts.append(text)

    # Insert the AUTO-GENERATED notice right after the shebang (line 1).
    header = parts[0]
    if header.startswith("#!"):
        shebang, nl, rest = header.partition("\n")
        parts[0] = shebang + nl + AUTOGEN + rest

    bundle = "\n\n".join(parts).rstrip() + "\n"
    OUT.write_text(bundle)
    OUT.chmod(0o755)
    n_lines = bundle.count("\n")
    print(f"built {OUT.relative_to(ROOT)}: {len(bundle):,} bytes, {n_lines:,} lines")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
